# TCL File Generated by Component Editor 23.1
# Sun Oct 20 18:55:15 MDT 2024
# DO NOT MODIFY


# 
#  "" v1.0
#  2024.10.20.18:55:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module 
# 
set_module_property DESCRIPTION ""
set_module_property NAME ""
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ""
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

